In [4]:
#Question 1:
#ne sachant pas la liste doit contenir les elements du tableau ou encore les Xij du tableau:

import numpy as np
liste = list() # creons une liste vide 
a = np.array([[1, 2, 3], [4, 5, 6]])# notre liste exemple pour l' exercice
print(a)#verifions le resultat 

b = a.tolist() #transformer le tableau en liste 
print(b) #verifions le resultat 
# essayons maintenant de transformer tout les elements Xij du tableau en list
for index, x in np.ndenumerate(a):#enumerons tous les elements du tableau
    print(index, x)#verifions le resultat
    liste.append(x)#ajoutons tous les elements à la liste vide 
print(liste)#verifions le resultat

[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
[1, 2, 3, 4, 5, 6]


In [5]:
#Question 2
import numpy as np
# creons la somme diagonale qui nous servira pour repondreà l' exercice
sommediag = 0
#creons le tableau unidimensionnel 
a = np.arange(0,15)
np.shape(a)
print(np.shape(a))#verifions le tableau
a.shape = (3,5)#transformons en tableau bi dimensionnel 
print(a)#verifions 
for i in range(0, len(a)) :#creer une boucle nous permettant de trier les elements du tableau 
    print(a[i,i])#ecrivons tous les elements de la diagonale ou i = j
    sommediag = sommediag + a[i,i]
print("la somme de elements de la diagonale du tableau :", sommediag)

(15,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
0
6
12
la somme de elements de la diagonale du tableau : 18


In [9]:
#Question 3 :
import numpy as np
a = np.arange(0,100)#creons les tableaux à utiliser
a.shape = (10,10)
b = np.array([[1, 3, 3],
                  [1, 4, 3],
                  [1, 3, 4]])
X = 2
#creons les tris des elements :
print("les elements du tableau superieur à X")
for index, x in np.ndenumerate(a):
    if x > X :
        print(x," l'index de l' element :", index)
print("les elements du tableau superieur à X")        
for index, g in np.ndenumerate(b):
    if g < X :
        print("les elements dont la valeur est superieurs à X",g,index)

les elements du tableau superieur à X
3  l'index de l' element : (0, 3)
4  l'index de l' element : (0, 4)
5  l'index de l' element : (0, 5)
6  l'index de l' element : (0, 6)
7  l'index de l' element : (0, 7)
8  l'index de l' element : (0, 8)
9  l'index de l' element : (0, 9)
10  l'index de l' element : (1, 0)
11  l'index de l' element : (1, 1)
12  l'index de l' element : (1, 2)
13  l'index de l' element : (1, 3)
14  l'index de l' element : (1, 4)
15  l'index de l' element : (1, 5)
16  l'index de l' element : (1, 6)
17  l'index de l' element : (1, 7)
18  l'index de l' element : (1, 8)
19  l'index de l' element : (1, 9)
20  l'index de l' element : (2, 0)
21  l'index de l' element : (2, 1)
22  l'index de l' element : (2, 2)
23  l'index de l' element : (2, 3)
24  l'index de l' element : (2, 4)
25  l'index de l' element : (2, 5)
26  l'index de l' element : (2, 6)
27  l'index de l' element : (2, 7)
28  l'index de l' element : (2, 8)
29  l'index de l' element : (2, 9)
30  l'index de l' elemen

In [1]:
#question 4

import numpy as np
#Creons deux matrices d' egales dimensions 
A = np.array([[ 1, 1, -2 ], [-1, 2, 1], [0, 1, -1]])
B = np.array([[ 3, 7, -6 ], [7, 6, 19], [8, 10, 9]])
#sommons les :
C = A+B
print("les sommes des deux matrices :", C)

les sommes des deux matrices : [[ 4  8 -8]
 [ 6  8 20]
 [ 8 11  8]]


In [2]:
#question 5 :
print(C) # utilisons le tableau de l' exeercice précédent
for i in range(0, len(C)) :# creons une boucle avec indexation 
    print("la moyenne de la ligne ", i+1 ,"du tableau", np.mean(C[i,]))# écrivons les moyennes de chaque ligne du table 
    

[[ 4  8 -8]
 [ 6  8 20]
 [ 8 11  8]]
la moyenne de la ligne  0 du tableau 1.3333333333333333
la moyenne de la ligne  1 du tableau 11.333333333333334
la moyenne de la ligne  2 du tableau 9.0
